// <auto-generated />
using System;
using BattleshipBoardGame.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BattleshipBoardGame.Migrations
{
    [DbContext(typeof(SimulationsDbContext))]
    [Migration("20231102234530_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("BattleshipBoardGame.Models.Entities.PlayerDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Guesses")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ships")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PlayerDto");
                });

            modelBuilder.Entity("BattleshipBoardGame.Models.Entities.Simulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("Player1Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Player2Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("BattleshipBoardGame.Models.Entities.PlayerDto", b =>
                {
                    b.OwnsOne("BattleshipBoardGame.Models.Entities.PlayerInfo", "PlayerInfo", b1 =>
                        {
                            b1.Property<Guid>("PlayerDtoId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("GuessingStrategy")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("ShipsPlacementStrategy")
                                .HasColumnType("INTEGER");

                            b1.HasKey("PlayerDtoId");

                            b1.ToTable("PlayerDto");

                            b1.WithOwner()
                                .HasForeignKey("PlayerDtoId");
                        });

                    b.Navigation("PlayerInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("BattleshipBoardGame.Models.Entities.Simulation", b =>
                {
                    b.HasOne("BattleshipBoardGame.Models.Entities.PlayerDto", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("BattleshipBoardGame.Models.Entities.PlayerDto", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.Navigation("Player1");

                    b.Navigation("Player2");
                });
#pragma warning restore 612, 618
        }
    }
}
